version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
  settings:
    errcheck:
      exclude-functions:
        - os.Remove
        - (*os.File).Close
        - (*os/exec.Cmd).Run
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
